services:

 postgres:
    image: postgres:18
    container_name: AUTOService-postgres
    environment:
      POSTGRES_DB: AUTOService
      POSTGRES_USER: postgres228
      POSTGRES_PASSWORD: roman228
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d AUTOService"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

 redis:
    image: redis
    container_name: AUTOService-redis
    ports:
      - "6379:6379"
 minio:
  image: minio/minio
  container_name: AUTOService-minio
  ports:
    - "9000:9000"
    - "9001:9001"
  environment:
    MINIO_ROOT_USER: minio_admin
    MINIO_ROOT_PASSWORD: minio_password
  volumes:
    - minio_data:/data
  command: server /data --console-address ":9001"

 # crm_system_backend:
 #    image: ${DOCKER_REGISTRY-}crmsystembackend
 #    build:
 #      context: .
 #      dockerfile: CRM_system_backend/Dockerfile

volumes:
  postgres_data:
  minio_data:
