services:

 postgres:
    image: postgres:18
    container_name: AUTOService-postgres
    environment:
      POSTGRES_DB: AUTOService
      POSTGRES_USER: postgres228
      POSTGRES_PASSWORD: roman228
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres228 -d AUTOService"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

 redis:
    image: redis
    container_name: AUTOService-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

 minio:
  image: minio/minio
  container_name: AUTOService-minio
  ports:
    - "9000:9000"
    - "9001:9001"
  environment:
    MINIO_ROOT_USER: minio_admin
    MINIO_ROOT_PASSWORD: minio_password
  volumes:
    - minio_data:/data
  command: server /data --console-address ":9001"
  healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 3

 crm_system_backend:
    build:
      context: ..
      dockerfile: Server/CRM_system_backend/Dockerfile
    container_name: AUTOService-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__SystemDbContext=Host=postgres;Port=5432;Database=AUTOService;Username=postgres228;Password=roman228
      - ConnectionStrings__Redis=redis:6379
      - Minio__ServiceUrl=http://minio:9000
      - Minio__AccessKey=minio_admin
      - Minio__SecretKey=minio_password
      - Minio__BucketName=service-files
      - JwtOptions__SecretKey=SecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKeySecretKey
      - JwtOptions__ExpiresHours=12
    ports:
      - "5066:8080" 
    volumes:
      - ./keys:/app/keys
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data:
  keys_storage:
