services:

 postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: AUTOServic
      POSTGRES_USER: postgres228
      POSTGRES_PASSWORD: roman228
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Carsharing"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

 # crm_system_backend:
 #    image: ${DOCKER_REGISTRY-}crmsystembackend
 #    build:
 #      context: .
 #      dockerfile: CRM_system_backend/Dockerfile

volumes:
  postgres_data:
